### ISSUE TITLE
Typo in reading cookies section

### ISSUE THREAD

**Issue by ghost** [oliverjam/learn-express#1]
`req.cookie` doesn't work. I think it should be `req.cookies`

I kept getting the error 'res.removeCookie is not a function' so I used `res.clearCookie` instead. Not sure I did something wrong or if this is a typo?

**Comment by oliverjam** [comment]
Sorry about all the typos! It is `req.cookies` and `clearCookie`, my brain clearly switched off while writing this 😅.

The `clearCookie` error was fixed here https://github.com/oliverjam/learn-express/commit/0402003bb08b927a4742337444820041483956dd
